import {
	Book,
	Briefcase,
	Car,
	Cat,
	Coffee,
	CreditCard,
	Dog,
	DollarSign,
	Dumbbell,
	Film,
	Gift,
	GraduationCap,
	Heart,
	Home,
	Lightbulb,
	type LucideIcon,
	Music,
	PiggyBank,
	Plane,
	Shirt,
	ShoppingCart,
	Sparkles,
	Utensils,
	Wallet,
} from "lucide-react";

export const AVAILABLE_ICONS: Record<string, LucideIcon> = {
	DollarSign,
	Heart,
	PiggyBank,
	ShoppingCart,
	Home,
	Lightbulb,
	Car,
	CreditCard,
	Utensils,
	Coffee,
	Plane,
	GraduationCap,
	Briefcase,
	Dumbbell,
	Music,
	Film,
	Book,
	Shirt,
	Gift,
	Dog,
	Cat,
	Sparkles,
	Wallet,
};

export const AVAILABLE_COLORS = [
	// Row 1: Light shades
	{ name: "Red Light", value: "#fca5a5", group: "Red" },
	{ name: "Orange Light", value: "#fdba74", group: "Orange" },
	{ name: "Yellow Light", value: "#fde047", group: "Yellow" },
	{ name: "Green Light", value: "#86efac", group: "Green" },
	{ name: "Teal Light", value: "#5eead4", group: "Teal" },
	{ name: "Blue Light", value: "#93c5fd", group: "Blue" },
	{ name: "Purple Light", value: "#c4b5fd", group: "Purple" },
	{ name: "Pink Light", value: "#f9a8d4", group: "Pink" },
	// Row 2: Dark shades
	{ name: "Red Dark", value: "#b91c1c", group: "Red" },
	{ name: "Orange Dark", value: "#c2410c", group: "Orange" },
	{ name: "Yellow Dark", value: "#a16207", group: "Yellow" },
	{ name: "Green Dark", value: "#15803d", group: "Green" },
	{ name: "Teal Dark", value: "#0f766e", group: "Teal" },
	{ name: "Blue Dark", value: "#1e40af", group: "Blue" },
	{ name: "Purple Dark", value: "#6d28d9", group: "Purple" },
	{ name: "Pink Dark", value: "#be185d", group: "Pink" },
];

export const DEFAULT_ICON = "Wallet";
export const DEFAULT_COLOR = "#3b82f6";
