/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTransactionsRouteImport } from './routes/app.transactions'
import { Route as AppRefreshRouteImport } from './routes/app.refresh'
import { Route as AppOverviewRouteImport } from './routes/app.overview'
import { Route as AppBudgetRouteImport } from './routes/app.budget'
import { Route as AppAccountsRouteImport } from './routes/app.accounts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/app/transactions',
  path: '/app/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRefreshRoute = AppRefreshRouteImport.update({
  id: '/app/refresh',
  path: '/app/refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/app/overview',
  path: '/app/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBudgetRoute = AppBudgetRouteImport.update({
  id: '/app/budget',
  path: '/app/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountsRoute = AppAccountsRouteImport.update({
  id: '/app/accounts',
  path: '/app/accounts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/refresh': typeof AppRefreshRoute
  '/app/transactions': typeof AppTransactionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/refresh': typeof AppRefreshRoute
  '/app/transactions': typeof AppTransactionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/accounts': typeof AppAccountsRoute
  '/app/budget': typeof AppBudgetRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/refresh': typeof AppRefreshRoute
  '/app/transactions': typeof AppTransactionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/accounts'
    | '/app/budget'
    | '/app/overview'
    | '/app/refresh'
    | '/app/transactions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/accounts'
    | '/app/budget'
    | '/app/overview'
    | '/app/refresh'
    | '/app/transactions'
  id:
    | '__root__'
    | '/'
    | '/app/accounts'
    | '/app/budget'
    | '/app/overview'
    | '/app/refresh'
    | '/app/transactions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppAccountsRoute: typeof AppAccountsRoute
  AppBudgetRoute: typeof AppBudgetRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppRefreshRoute: typeof AppRefreshRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/transactions': {
      id: '/app/transactions'
      path: '/app/transactions'
      fullPath: '/app/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/refresh': {
      id: '/app/refresh'
      path: '/app/refresh'
      fullPath: '/app/refresh'
      preLoaderRoute: typeof AppRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/overview': {
      id: '/app/overview'
      path: '/app/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/budget': {
      id: '/app/budget'
      path: '/app/budget'
      fullPath: '/app/budget'
      preLoaderRoute: typeof AppBudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/accounts': {
      id: '/app/accounts'
      path: '/app/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppAccountsRoute: AppAccountsRoute,
  AppBudgetRoute: AppBudgetRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppRefreshRoute: AppRefreshRoute,
  AppTransactionsRoute: AppTransactionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
